### ISSUE TITLE
Some question about the equation

### ISSUE THREAD

**Issue by hellofinch** [exalearn/cahnhilliard_2d#1]
The Cahn-Hilliard equation shown in README.md is modified as you say. May I ask the equation reference from where? What is the meaning of the last term?

I find [`cpp/src/utils_ch.cpp:3`](https://github.com/exalearn/cahnhilliard_2d/blob/docker-devel/cpp/src/utils_ch.cpp#L3). All terms are here but not the last one.

**Comment by rvinaybharadwaj** [comment]
@aik7 Can you take a look?

**Comment by aik7** [comment]
@hellofinch, I am not the developer of this repository.  You can ask the developer, Anthony DeGennaro, but he is not funded by this project anymore.

**Comment by rvinaybharadwaj** [comment]
I would suggest creating an issue in the cahnhilliard repository itself, as this is outside the purview of EXARL.

**Comment by adegenna** [comment]
Hi everyone. Here's some info I can provide:

_May I ask the equation reference from where?_
Try Choksi and Ren, 2003:
https://link.springer.com/content/pdf/10.1023/A:1025722804873.pdf

_What is the meaning of the last term?_
That last term (\sigma \eta) was a relic from when I was trying to put in stochastic behavior to the system. It was intended to be the type of random, "white noise" perturbation term that you see in stochastic ODEs (like an Ornstein-Uhlenbeck equation). Anyway I never did anything with it, so it should be removed from the README.

I hope this helps.

**Comment by hellofinch** [comment]
Thank you for your response. @adegenna @aik7 @rvinaybharadwaj
